[package]
name = "parser-rs"
version = "0.1.0"
edition = "2021"


[dependencies]
indexmap = {version = "2.7.0", features = ["serde"]}
jsonschema = "0.28.1"
serde = {version = "1.0.104", features = ["derive"]}
serde_json = "1.0.135"
serde_yaml = "0.9.34"
